spring:
  application:
    name: reactive
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spring_reactive
    username: postgres
    password: esscsmfu2
  flyway:
    url: jdbc:postgresql://localhost:5432/spring_reactive
    user: postgres
    password: esscsmfu2
